### ISSUE TITLE
error: fastBPE/fastBPE.cpp: no such file or directory

### ISSUE THREAD

**Issue by vince-lynch** [minimaxir/ctrl-gce#7]
Hi, 
Not sure the reason I'm having problems installing fastBPE following your exact steps with google compute engine.
I already tried it on paperspace notebook (v100) and fastBPE installed fine as far as I recall (however the interactive console didn't load, unsure why).

Anyway, I will google about "error: fastBPE/fastBPE.cpp: no such file or directory"

**Comment by vince-lynch** [comment]
Sorry, it was some python 2 vs python 3. pip vs pip3 install issue.

cd fastBPE
sudo python3 setup.py install

I'll work it out.

**Comment by vince-lynch** [comment]
Change the line in the .sh 
from: pip install Cython
to: sudo python -m pip install Cython

**Comment by vince-lynch** [comment]
Actually even after that, I still got the same error that I was already experiencing through my paperspace setup.

  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From generation.py:132: The name tf.train.AdagradOptimizer is deprecated. Please use tf.compat.v1.train.AdagradOptimizer instead.

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                    
==================================================================================================
input_1 (InputLayer)            [(None, 256)]        0                                            
__________________________________________________________________________________________________
tied_embedding_softmax (TiedEmb multiple             315810054   input_1[0][0]                    
                                                                 encoder[0][0]                    
__________________________________________________________________________________________________
encoder (Encoder)               (None, 256, 1280)    1322154496  tied_embedding_softmax[0][0]    
==================================================================================================
Total params: 1,637,964,550
Trainable params: 1,637,964,550
Non-trainable params: 0
__________________________________________________________________________________________________
None
WARNING:tensorflow:You are creating an Estimator from a Keras model manually subclassed from `Model`, that was already called on some inputs (and thus already had weights). We are currently unable to preserve the model's state (its weights) as part of the estimator in this case. Be warned that the estimator has been created using a freshly initialized version of your model.
Note that this doesn't affect the state of the model instance you passed as `keras_model` argument.
WARNING:tensorflow:Estimator's model_fn (<function model_fn at 0x7fc65a8fe938>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:From generation.py:156: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

Traceback (most recent call last):
  File "generation.py", line 158, in <module>
    predict_fn = tf.contrib.predictor.from_estimator(estimator_model, serving_input_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/contrib/predictor/predictor_factories.py", line 105, in from_estimator
    config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/contrib/predictor/core_estimator_predictor.py", line 72, in __init__
    serving_input_receiver, estimator, output_key)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/contrib/predictor/core_estimator_predictor.py", line 37, in _get_signature_def
    estimator.config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 250, in public_model_fn
    return self._call_model_fn(features, labels, mode, config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1149, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/keras.py", line 288, in model_fn
    optimizer_config=optimizer_config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/keras.py", line 227, in _clone_and_build_model
    optimizer_config=optimizer_config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/models.py", line 621, in clone_and_build_model
    clone = clone_model(model, input_tensors=input_tensors)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/models.py", line 409, in clone_model
    model, input_tensors=input_tensors, layer_fn=clone_function)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/models.py", line 210, in _clone_functional_model
    tensor_map)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/models.py", line 97, in _make_new_nodes
    new_layer = layer_fn(layer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/models.py", line 57, in _clone_layer
    return layer.__class__.from_config(layer.get_config())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 580, in get_config
    raise NotImplementedError('Layers with arguments in `__init__` must '
NotImplementedError: Layers with arguments in `__init__` must override `get_config`.

**Comment by micyan01** [comment]
> Change the line in the .sh from: pip install Cython to: sudo python -m pip install Cython

this works after I installed Cython
